### ISSUE TITLE
Random Shakespeare Quotes...

### ISSUE THREAD

**Issue by datahead8888** [Secretchronicles/furbot#4]
Ut oh!  Dr. M has hijacked furbot and reprogrammed him to start making Shakespeare quotes!  What will we do?

Tasks:
* Allow furbot to read a simple text file of Shakespeare quotes (or multiple files with different kinds of quotes) with one per line
* Allow furbot to be configured to either give quotes when people enter or not give quotes at this time.  Allow a value to be specified for the percentage of the time he gives such quotes.
* Allow furbot to be configured to give a quote when certain text is detected in a user's IRC discussion
* Implement a command that can be used in IRC to directly request a quote (either a random quote or a specific quote number)

**Comment by datahead8888** [comment]
Can this task be closed?

**Comment by Quintus** [comment]
Yes.
